#baseURL = "http://localhost:1313"
baseURL = "https://frnd.design/"
languageCode = "en-us"
publishDir = "public"
staticDir = "static"
uploadDir = "static/uploads"
title = "Fernando Soares — Designer de Interfaces"
summaryLength = 30
canonifyURLs = true
relativeURLs = true

[Author]
    name = "Fernando Soares"

[Params]
    ghrepo = ""
    title = "Fernando Soares - Designer de Interfaces"
    description = "Portfolio e blog de Fernando Soares."

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[taxonomies]
    tag = "tags"
    category = "categories"

[menu]
    [[menu.main]]
        name = "Home"
        pageref = "/"
        weight = 1
        pre = ''
    [[menu.main]]
        name = "Sobre"
        pageref = "/sobre/"
        weight = 2
        pre = ''
    [[menu.main]]
        name = "Portfolio"
        url = "https://dribbble.com/fernando"
        weight = 3
        pre = ''
        [menu.main.params]
            external = true
    [[menu.main]]
        name = "Notes"
        pageref = "/notes/"
        weight = 4
        pre = ''