#baseURL = "http://localhost:1313"
baseURL = "https://frnd.design/"
languageCode = "en-us"
publishDir = "public"
staticDir = "static"
uploadDir = "static/uploads"
title = "Fernando Soares - Designer e Desenvolvedor de Interfaces"
summaryLength = 30
canonifyURLs = true
relativeURLs = true

[Author]
    name = "Fernando Soares"

[Params]
    ghrepo = ""
    title = "Fernando Soares - Designer e Desenvolvedor de Interfaces"
    description = "Portfolio e blog de Fernando Soares."

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[taxonomies]
    tag = "tags"
    category = "categories"