#baseURL = "http://localhost:1313"
baseURL = "https://frrrnd.github.io/"
languageCode = "en-us"
publishDir = "public"
title = "Fernando Soares - UX, UI & Front End Design"

[Author]
    name = "Fernando Soares"

[Params]
    ghrepo = ""
    title = "Fernando Soares - UX, UI & Front End Design"
    description = "Portfolio e blog de Fernando Soares."